In [24]:
import numpy as pd
import pandas as pd

In [25]:
df = pd.read_csv('/content/train.csv')

In [26]:
df.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

In [27]:
#get the independent feature
x = df.drop('label',axis=1)

In [28]:
x.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  
0  House Dem Aide: We Didn’t Even See Comey’s Let...  
1  Ever get the feeling your life circles the rou...  
2  Why the Truth Might Get You Fired October 29, ...  
3  Videos 15 Civilians Killed In Single US Airstr...  
4  Print \nAn Iranian woman has been sentenced to...

In [29]:
#get dependent feature
y =df['label']

In [30]:
y.head()

0    1
1    0
2    1
3    1
4    1
Name: label, dtype: int64

In [31]:
df.shape

(20800, 5)

In [32]:
from sklearn.feature_extraction.text import CountVectorizer,TfidfVectorizer,HashingVectorizer

In [33]:
df = df.dropna()

In [34]:
df.shape

(18285, 5)

In [35]:
messages = df.copy()

In [36]:
messages.reset_index(inplace=True)

In [37]:
messages.head(10)

index  id                                              title  \
0      0   0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1      1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2      2   2                  Why the Truth Might Get You Fired   
3      3   3  15 Civilians Killed In Single US Airstrike Hav...   
4      4   4  Iranian woman jailed for fictional unpublished...   
5      5   5  Jackie Mason: Hollywood Would Love Trump if He...   
6      7   7  Benoît Hamon Wins French Socialist Party’s Pre...   
7      9   9  A Back-Channel Plan for Ukraine and Russia, Co...   
8     10  10  Obama’s Organizing for Action Partners with So...   
9     11  11  BBC Comedy Sketch "Real Housewives of ISIS" Ca...   

                         author  \
0                 Darrell Lucus   
1               Daniel J. Flynn   
2            Consortiumnews.com   
3               Jessica Purkiss   
4                Howard Portnoy   
5               Daniel Nussbaum   
6               Alissa J. Rubin   
7  Megan Twohey and Scott Shane   
8                   Aaron Klein   
9               Chris Tomlinson   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1  
5  In these trying times, Jackie Mason is the Voi...      0  
6  PARIS  —   France chose an idealistic, traditi...      0  
7  A week before Michael T. Flynn resigned as nat...      0  
8  Organizing for Action, the activist group that...      0  
9  The BBC produced spoof on the “Real Housewives...      0

In [38]:
messages['title'][6]

'Benoît Hamon Wins French Socialist Party’s Presidential Nomination - The New York Times'

In [39]:
import nltk

In [40]:
nltk.download('stopwords')


[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [41]:
#apply stopword remove sapces , dot,- , regular expresion etc
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
import re

ps = PorterStemmer()

corpus = []
for i in range(0,len(messages)):
    review = re.sub('[^a-zA-Z\s.-]', ' ' , messages['text'][i])
    review = review.lower()
    review = review.split()

    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

In [42]:
print(corpus[3])

video civilian kill singl us airstrik identifi rate civilian kill american airstrik afghanistan higher us engag activ combat operations. photo hellfir missil load onto us militari reaper drone afghanistan staff sgt. brian ferguson u.s. air force. bureau abl identifi civilian kill singl us drone strike afghanistan last month biggest loss civilian life one strike sinc attack medecin san frontier hospit msf last october. us claim conduct counter-terror strike islam state fighter hit nangarhar provinc missil septemb . next day unit nation issu unusu rapid strong statement say strike kill civilian injur other gather hous celebr tribal elder return pilgrimag mecca. bureau spoke man name haji rai said owner hous targeted. said peopl kill other injur provid name list . bureau abl independ verifi ident died. rai son headmast local school among them. anoth man abdul hakim lost three son attack. rai said involv deni us claim member visit hous strike. said even speak sort peopl phone let alon rece

In [43]:
#Apply bag of words
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer(max_features=5000 , ngram_range=(1,3))
x = tfidf.fit_transform(corpus).toarray()

In [44]:
x.shape

(18285, 5000)

In [45]:
y = messages['label']

In [46]:
from sklearn.model_selection import train_test_split
x_train , x_test , y_train , y_test = train_test_split(x,y,test_size=0.33,random_state=0)

In [47]:
# Access the feature names from the CountVectorizer's vocabulary_
feature_names = tfidf.get_feature_names_out()

# Print the first 20 feature names
print(feature_names[:20])


['aaron' 'abandon' 'abc' 'abe' 'abedin' 'abil' 'abl' 'abort' 'about'
 'abroad' 'absenc' 'absolut' 'absorb' 'absurd' 'abu' 'abus' 'academ'
 'academi' 'acceler' 'accept']


In [48]:
params_names = tfidf.get_params()

print(params_names)

{'analyzer': 'word', 'binary': False, 'decode_error': 'strict', 'dtype': <class 'numpy.float64'>, 'encoding': 'utf-8', 'input': 'content', 'lowercase': True, 'max_df': 1.0, 'max_features': 5000, 'min_df': 1, 'ngram_range': (1, 3), 'norm': 'l2', 'preprocessor': None, 'smooth_idf': True, 'stop_words': None, 'strip_accents': None, 'sublinear_tf': False, 'token_pattern': '(?u)\\b\\w\\w+\\b', 'tokenizer': None, 'use_idf': True, 'vocabulary': None}


In [49]:
#show now how dataset is look like
count_df = pd.DataFrame(x_train,columns=tfidf.get_feature_names_out())

In [50]:
count_df.head()

aaron  abandon  abc  abe  abedin  abil  abl  abort  about  abroad  ...  \
0    0.0      0.0  0.0  0.0     0.0   0.0  0.0    0.0    0.0     0.0  ...   
1    0.0      0.0  0.0  0.0     0.0   0.0  0.0    0.0    0.0     0.0  ...   
2    0.0      0.0  0.0  0.0     0.0   0.0  0.0    0.0    0.0     0.0  ...   
3    0.0      0.0  0.0  0.0     0.0   0.0  0.0    0.0    0.0     0.0  ...   
4    0.0      0.0  0.0  0.0     0.0   0.0  0.0    0.0    0.0     0.0  ...   

      young  young peopl  younger  youth  youtub  zero  zika  zionist  zone  \
0  0.203643          0.0      0.0    0.0     0.0   0.0   0.0      0.0   0.0   
1  0.000000          0.0      0.0    0.0     0.0   0.0   0.0      0.0   0.0   
2  0.000000          0.0      0.0    0.0     0.0   0.0   0.0      0.0   0.0   
3  0.000000          0.0      0.0    0.0     0.0   0.0   0.0      0.0   0.0   
4  0.000000          0.0      0.0    0.0     0.0   0.0   0.0      0.0   0.0   

    zu  
0  0.0  
1  0.0  
2  0.0  
3  0.0  
4  0.0  

[5 rows x 5000 columns]

In [51]:
#Apply ML Model
from sklearn.naive_bayes import MultinomialNB
classifier = MultinomialNB()

In [52]:
classifier.fit(x_train,y_train)

MultinomialNB()

In [53]:
pred = classifier.predict(x_test)

In [54]:
print(pred)

[0 0 1 ... 0 0 0]


In [55]:
from sklearn.metrics import accuracy_score ,confusion_matrix

In [56]:
cm = confusion_matrix(y_test,pred)

In [57]:
cm

array([[3244,  145],
       [ 439, 2207]])

In [58]:
cm

array([[3244,  145],
       [ 439, 2207]])

In [59]:
acc_score = accuracy_score(y_test,pred)

In [60]:
acc_score

0.9032311516155758

In [61]:
#Multinominal classifer with Hyperparameter
classifier = MultinomialNB(alpha=0.1)

In [62]:
import numpy as np
previous_score=0
for alpha in np.arange(0,1,0.1):
    sub_classifier=MultinomialNB(alpha=alpha)
    sub_classifier.fit(x_train,y_train)
    y_pred=sub_classifier.predict(x_test)
    acc_score = accuracy_score(y_test,pred)
    if acc_score>previous_score:
        classifier=sub_classifier
    print("Alpha: {}, Score : {}".format(alpha,acc_score))

/usr/local/lib/python3.10/dist-packages/sklearn/naive_bayes.py:629: FutureWarning: The default value for `force_alpha` will change to `True` in 1.4. To suppress this warning, manually set the value of `force_alpha`.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/naive_bayes.py:635: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(


Alpha: 0.0, Score : 0.9032311516155758
Alpha: 0.1, Score : 0.9032311516155758
Alpha: 0.2, Score : 0.9032311516155758
Alpha: 0.30000000000000004, Score : 0.9032311516155758
Alpha: 0.4, Score : 0.9032311516155758
Alpha: 0.5, Score : 0.9032311516155758
Alpha: 0.6000000000000001, Score : 0.9032311516155758
Alpha: 0.7000000000000001, Score : 0.9032311516155758
Alpha: 0.8, Score : 0.9032311516155758
Alpha: 0.9, Score : 0.9032311516155758


In [63]:
feature_names = tfidf.get_feature_names_out()

In [64]:

# Assuming you are interested in the most relevant words for class 0 (negative class)
class_index = 1

# Access the feature log probabilities for the class of interest
feature_log_probabilities = classifier.feature_log_prob_

# Get the feature names from the CountVectorizer
feature_names = tfidf.get_feature_names_out()

# Get the indices of the words with the highest feature log probabilities for the class
top_word_indices = np.argsort(feature_log_probabilities[class_index])[::-1]

# Show the top N words (e.g., top 10) with the highest feature log probabilities
top_N = 20
top_words = [feature_names[i] for i in top_word_indices[:top_N]]

print(f"Most relevant words for class {class_index}:")
print(top_words)


Most relevant words for class 1:
['clinton', 'trump', 'hillari', 'us', 'elect', 'vote', 'peopl', 'one', 'state', 'email', 'hillari clinton', 'fbi', 'would', 'like', 'american', 'war', 'world', 'time', 'octob', 'use']


In [65]:
# Assuming you are interested in the most irrelevant words for class 0 (negative class)
class_index = 1

# Access the feature log probabilities for the class of interest
feature_log_probabilities = classifier.feature_log_prob_

# Get the feature names from the CountVectorizer
feature_names = tfidf.get_feature_names_out()

# Get the indices of the words with the most negative feature log probabilities for the class
top_word_indices = np.argsort(feature_log_probabilities[class_index])

# Show the top N words (e.g., top 10) with the most negative feature log probabilities
top_N = 5000
top_words = [(feature_names[i], feature_log_probabilities[class_index][i]) for i in top_word_indices[:top_N]]

print(f"Most irrelevant words for class {class_index}:")
for word, coefficient in top_words:
    print(f"Coefficient: {coefficient:.4f}, Word: {word}")

Streaming output truncated to the last 5000 lines.
Coefficient: -10.9953, Word: mr de
Coefficient: -10.9953, Word: mr ail
Coefficient: -10.9953, Word: mr roof
Coefficient: -10.9953, Word: mr bannon
Coefficient: -10.9953, Word: mr castro
Coefficient: -10.9953, Word: mr kushner
Coefficient: -10.9953, Word: judg gorsuch
Coefficient: -10.9953, Word: mr sander
Coefficient: -10.9953, Word: follow pam key
Coefficient: -10.9953, Word: follow pam
Coefficient: -10.9953, Word: year mr
Coefficient: -10.9953, Word: mr cruz
Coefficient: -10.9953, Word: pruitt
Coefficient: -10.9953, Word: key twitter pamkeynen
Coefficient: -10.9953, Word: key twitter
Coefficient: -10.9953, Word: mr christi
Coefficient: -10.9953, Word: mr flynn
Coefficient: -10.9953, Word: mr scott
Coefficient: -10.9953, Word: gold medal
Coefficient: -10.9953, Word: brief post
Coefficient: -10.9953, Word: ms trump
Coefficient: -10.9953, Word: pamkeynen
Coefficient: -10.9953, Word: pam key twitter
Coefficient: -10.9953, Word: mr xi
Coe