In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [5]:
sent = ['the glass of milk',
       'the glass of juice',
       'the cup of tea',
       'I am a good boy',
       'I am a good developer',
       'understand the meaninng of words',
       'your videos are good']

In [6]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaninng of words',
 'your videos are good']

In [7]:
voc_size = 10000

In [8]:
#one hot representation
onehot_rep = [one_hot(words,voc_size)for words in sent]
print(onehot_rep)

[[3701, 9374, 1288, 5522], [3701, 9374, 1288, 9251], [3701, 7904, 1288, 6760], [7777, 5694, 4483, 3245, 1515], [7777, 5694, 4483, 3245, 2476], [945, 3701, 7485, 1288, 4951], [3062, 7717, 7070, 3245]]


In [9]:
#word embedding representation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [10]:
import numpy as np

In [12]:
sent_length = 8
embedded_doc = pad_sequences(onehot_rep, padding='pre' , maxlen= sent_length)
print(embedded_doc)

[[   0    0    0    0 3701 9374 1288 5522]
 [   0    0    0    0 3701 9374 1288 9251]
 [   0    0    0    0 3701 7904 1288 6760]
 [   0    0    0 7777 5694 4483 3245 1515]
 [   0    0    0 7777 5694 4483 3245 2476]
 [   0    0    0  945 3701 7485 1288 4951]
 [   0    0    0    0 3062 7717 7070 3245]]


In [13]:
dim = 10

In [14]:
model = Sequential()
model.add(Embedding(voc_size,10,input_length = sent_length))
model.compile('adam','mse')

In [15]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [16]:
print(model.predict(embedded_doc))

[[[-2.60013230e-02 -4.86887954e-02  1.91603042e-02  1.38171650e-02
   -1.23822317e-02 -4.24216650e-02 -3.76272202e-03 -1.25380643e-02
    4.09395434e-02  2.00884417e-03]
  [-2.60013230e-02 -4.86887954e-02  1.91603042e-02  1.38171650e-02
   -1.23822317e-02 -4.24216650e-02 -3.76272202e-03 -1.25380643e-02
    4.09395434e-02  2.00884417e-03]
  [-2.60013230e-02 -4.86887954e-02  1.91603042e-02  1.38171650e-02
   -1.23822317e-02 -4.24216650e-02 -3.76272202e-03 -1.25380643e-02
    4.09395434e-02  2.00884417e-03]
  [-2.60013230e-02 -4.86887954e-02  1.91603042e-02  1.38171650e-02
   -1.23822317e-02 -4.24216650e-02 -3.76272202e-03 -1.25380643e-02
    4.09395434e-02  2.00884417e-03]
  [-2.18630079e-02 -3.01360972e-02 -2.68908385e-02 -2.65210997e-02
    1.08939186e-02  1.07675306e-02 -3.86461988e-02  2.93663777e-02
   -3.49107273e-02 -3.79962325e-02]
  [ 3.71132754e-02 -2.99699605e-05 -3.31995487e-02  2.98008956e-02
    7.11428002e-03 -1.36559606e-02  3.95608284e-02 -4.01434787e-02
    2.40622833e-

In [17]:
embedded_doc[0]

array([   0,    0,    0,    0, 3701, 9374, 1288, 5522])

In [18]:
print(model.predict(embedded_doc[0]))

[[-2.60013230e-02 -4.86887954e-02  1.91603042e-02  1.38171650e-02
  -1.23822317e-02 -4.24216650e-02 -3.76272202e-03 -1.25380643e-02
   4.09395434e-02  2.00884417e-03]
 [-2.60013230e-02 -4.86887954e-02  1.91603042e-02  1.38171650e-02
  -1.23822317e-02 -4.24216650e-02 -3.76272202e-03 -1.25380643e-02
   4.09395434e-02  2.00884417e-03]
 [-2.60013230e-02 -4.86887954e-02  1.91603042e-02  1.38171650e-02
  -1.23822317e-02 -4.24216650e-02 -3.76272202e-03 -1.25380643e-02
   4.09395434e-02  2.00884417e-03]
 [-2.60013230e-02 -4.86887954e-02  1.91603042e-02  1.38171650e-02
  -1.23822317e-02 -4.24216650e-02 -3.76272202e-03 -1.25380643e-02
   4.09395434e-02  2.00884417e-03]
 [-2.18630079e-02 -3.01360972e-02 -2.68908385e-02 -2.65210997e-02
   1.08939186e-02  1.07675306e-02 -3.86461988e-02  2.93663777e-02
  -3.49107273e-02 -3.79962325e-02]
 [ 3.71132754e-02 -2.99699605e-05 -3.31995487e-02  2.98008956e-02
   7.11428002e-03 -1.36559606e-02  3.95608284e-02 -4.01434787e-02
   2.40622833e-03  3.53424214e-02